// <auto-generated />
using System;
using FinalProjectWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectWebAPI.Migrations
{
    [DbContext(typeof(FoodContext))]
    [Migration("20221201205947_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProjectWebAPI.Controllers.Hobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Days")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Days = "Everyday",
                            Hobby = "Studying the bible",
                            Name = "Mo Daniel",
                            Reason = "To Know who I am"
                        });
                });

            modelBuilder.Entity("FinalProjectWebAPI.FoodModels.Show", b =>
                {
                    b.Property<int>("ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowID"), 1L, 1);

                    b.Property<string>("Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seasons")
                        .HasColumnType("int");

                    b.Property<string>("ShowsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhereToWatch")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShowID");

                    b.ToTable("Shows");

                    b.HasData(
                        new
                        {
                            ShowID = 1,
                            Person = "Grant Kollar",
                            Seasons = 23,
                            ShowsName = "South Park",
                            WhereToWatch = "YouTube TV"
                        },
                        new
                        {
                            ShowID = 2,
                            Person = "Jacob",
                            Seasons = 3,
                            ShowsName = "The Boys",
                            WhereToWatch = "Amazon"
                        });
                });

            modelBuilder.Entity("FinalProjectWebAPI.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodId"), 1L, 1);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Calories = 150,
                            Group = "Fruit",
                            Name = "Strawberries",
                            Price = 10.99
                        });
                });

            modelBuilder.Entity("FinalProjectWebAPI.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthday = new DateTime(2002, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nathan Burns",
                            Program = "Information Technology",
                            Year = "2nd Year"
                        },
                        new
                        {
                            ID = 2,
                            Birthday = new DateTime(2001, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ryan Durham",
                            Program = "Information Technology",
                            Year = "4th Year"
                        },
                        new
                        {
                            ID = 3,
                            Birthday = new DateTime(2003, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Modupeoluwa Daniel",
                            Program = "Information Technology",
                            Year = "3rd Year"
                        },
                        new
                        {
                            ID = 4,
                            Birthday = new DateTime(2000, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grant Kollar",
                            Program = "Cyber Security",
                            Year = "5th Year"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
