// <auto-generated />
using System;
using FinalProjectWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectWebAPI.Migrations
{
    [DbContext(typeof(PersonContext))]
    partial class PersonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProjectWebAPI.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthday = new DateTime(2002, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nathan Burns",
                            Program = "Information Technology",
                            Year = "2nd Year"
                        },
                        new
                        {
                            ID = 2,
                            Birthday = new DateTime(2001, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ryan Durham",
                            Program = "Information Technology",
                            Year = "4th Year"
                        },
                        new
                        {
                            ID = 3,
                            Birthday = new DateTime(2003, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Modupeoluwa Daniel",
                            Program = "Information Technology",
                            Year = "3rd Year"
                        },
                        new
                        {
                            ID = 4,
                            Birthday = new DateTime(2000, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grant Kollar",
                            Program = "Cyber Security",
                            Year = "5th Year"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
